version: '4'
name: movie-app-db
services:
  mongoDB:
    image: postgres:latest
    container_name: postgresql_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
